### ISSUE TITLE
Configurable service list and access token for Facebook

### ISSUE THREAD

**Issue by IvanShymanovich** [heiseonline/shariff-backend-node#5]
Hi,
Some social APIs are working very slow, and if you need counts only from Facebook, LinkedIn and Twitter, you are forced to wait responses from all provided services. Waiting can take more than 10 seconds. It would be great to have configurable list of used services. 
Also Facebook limits requests to it's without access token and it make sense to add it, as well in php backend.
Thanks.

**Comment by IvanShymanovich** [comment]
i've added pull request with my implementation of these features and some else. 
https://github.com/heiseonline/shariff-backend-node/pull/6
if it is ok for you, feel free to use it :)

**Comment by compeak** [comment]
I am closing this issue because we are deprecating the node backend.
