### ISSUE TITLE
Empty answer

### ISSUE THREAD

**Issue by zoh48gz04** [heiseonline/shariff-backend-node#7]
Hi,

I installed the node backend on a Linux machine. When testing the installation by visiting "http://localhost:3001/?url=www.example.com", I just get an empty page (also via curl). The node-backend says the following: "160114/151216.252, request, http://0.0.0.0:3001: get / {"url":"www.example.com"} 200 (150ms)"

Is there any way, I can debug this? Unfortunately I'm not that qualified in node.

**Comment by compeak** [comment]
I am closing this issue because we are deprecating the node backend.
